In [1]:
with open("DTStest.txt","r") as file1:
    filestuff = file1.read()
    print(filestuff)

Line 1
Line 2
Line 3
Line 4


In [2]:
with open("DTStest.txt","r") as file1:
    lines = file1.readlines(2)
    print(lines)

['Line 1\n']


In [3]:
with open("DTStest.txt", "r") as file1:
    line = file1.readline()
    print(line)
    line = file1.readline()
    print(line)    

Line 1

Line 2



In [4]:
with open("DTStest.txt", "r") as file1:
    for line in file1:
        print(line)

Line 1

Line 2

Line 3

Line 4


In [5]:
with open ("outputfile.txt","w") as file1:
    file1.write("Output line 1\n")
    file1.write("Output line 2\n")

In [9]:
mylist = ["Hallo", "Hai", "Apa kabar", "semuanya"]
with open("outputfile2.txt","w") as file1:
    for l in mylist:
        file1.write(l)
        file1.write("\n")

In [20]:
mylist = ["Ini", "Kelas","DTS", "Data Science"]
with open("outputfile2.txt","a") as file1:
    for l in mylist:
        file1.write(l)
        file1.write("\n")

In [23]:
import pandas as pd
df = pd.read_csv("test.csv")
df.head()

Id   Open Date            City  City Group Type  P1   P2   P3   P4  P5  \
0   0  01/22/2011           Niğde       Other   FC   1  4.0  4.0  4.0   1   
1   1  03/18/2011           Konya       Other   IL   3  4.0  4.0  4.0   2   
2   2  10/30/2013          Ankara  Big Cities   FC   3  4.0  4.0  4.0   2   
3   3  05/06/2013         Kocaeli       Other   IL   2  4.0  4.0  4.0   2   
4   4  07/31/2013  Afyonkarahisar       Other   FC   2  4.0  4.0  4.0   1   

   ...  P28  P29  P30  P31  P32  P33  P34  P35  P36  P37  
0  ...  2.0  3.0    0    0    0    0    0    0    0    0  
1  ...  1.0  3.0    0    0    0    0    0    0    0    0  
2  ...  2.0  3.0    0    0    0    0    0    0    0    0  
3  ...  2.0  3.0    0    4    0    0    0    0    0    0  
4  ...  5.0  3.0    0    0    0    0    0    0    0    0  

[5 rows x 42 columns]

In [27]:
df.to_csv('newdf.csv')

In [28]:
list1 = [1,2,3,4,5,6,7,8,9]

In [29]:
import numpy as np

In [31]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [32]:
arr2 = np.array(list1)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr3 = arr2 * 2
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
type(arr1)

numpy.ndarray

In [39]:
arr1

array([1, 2, 3, 4])

In [40]:
arr1.dtype
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)

1
4
(4,)


In [41]:
arr2[2:5]

array([3, 4, 5])

In [42]:
u = arr1
v = np.array([3,4,5,6])
print(u)
print(v)

[1 2 3 4]
[3 4 5 6]


In [43]:
u+v

array([ 4,  6,  8, 10])

In [44]:
u-v

array([-2, -2, -2, -2])

In [45]:
u*2

array([2, 4, 6, 8])

In [46]:
z = []
for n,m in zip(u,v):
    z.append([n,m])

In [47]:
z

[[1, 3], [2, 4], [3, 5], [4, 6]]

In [48]:
type(z)
z = np.array(z)

In [49]:
z

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 6]])

In [50]:
print(z.ndim)
print(z.size)
print(z.shape)

2
8
(4, 2)


In [51]:
x = np.dot(u,v)

In [52]:
x

50

In [53]:
z

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 6]])

In [55]:
w = np.array([[1,2,3],[4,5,6]])
w

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
z = []
y = np.array([1,2])
for n,m in zip(u,y):
    z.append([n,m])
z

[[1, 1], [2, 2]]